export {default as Register} from "./register";
export {default as Login} from "./login";
export {default as Dashboard} from "./dashboard";
export {default as Profile} from "./profile";
export {default as Tabledashboard} from "./tabledashboard";
export {default as Page404} from "./page404";
export {default as Adduser} from "./adduser";
export  {default as Edituser} from "./edituser";
export {default as Formformik} from "./formformik";